[package]
name = "nvix"
version = "0.1.0"
edition = "2021"
author = "Zusier"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = 3

[dependencies]
clap = { version = "3.2.12", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["json", "blocking"] }
tokio = { version = "1.20.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
quick-xml = { version = "0.23.0", features = ["serialize"] }
tokio-test = { version = "0.4.2" }